### ISSUE TITLE
"x" delete not deleting or copying

### ISSUE THREAD

**Issue by qabulin** [paul-reilly/zbs-vim#1]
https://github.com/paul-reilly/zbs-vim/blob/84bbfc5e04f58bf2c4627341eda5349f41d0cb49/vim-mode.lua#L615-L616

I had to comment out lines 615 and 616 just to get "x" to delete, but even so, it still does not copy.  I'm having trouble reverse-engineering and understanding what's causing this behavior.

my environment:
ZeroBrane Studio (1.70; MobDebug 0.702)
macOS 10.13.3 (17D47)

**Comment by paul-reilly** [comment]
Thanks for reporting, yes 'x' worked in visual mode but not in normal mode for lines. I've fixed it and pushed an incorrectly named commit for it. :)

**Comment by paul-reilly** [comment]
So that commit works, but not like Vim. I'll change it later.

**Comment by paul-reilly** [comment]
Sorry for the delay, that's should be it working more as expected.
